INSERT INTO Login VALUES ("hugo","leboss","SU");
INSERT INTO Login VALUES ("misao","lechien","ADM");
INSERT INTO Login VALUES ("theo","pasbo","SU");
INSERT INTO Produit VALUES (40,"Tome 1",7.99,"img/tome1.jpg","manga","Tome 1 de One piece");
INSERT INTO Produit VALUES (40,"Tome 2",7.99,"img/tome2.jpg","manga","Tome 2 de One piece");
INSERT INTO Produit VALUES (35,"Tome 3",7.99,"img/tome3.jpg","manga","Tome 3 de One piece");
INSERT INTO Produit VALUES (35,"Tome 4",7.99,"img/tome4.jpg","manga","Tome 4 de One piece");
INSERT INTO Produit VALUES (40,"Tome 5",7.99,"img/tome5.jpg","manga","Tome 5 de One piece");
INSERT INTO Produit VALUES (20,"Luffy",30,"img/luffy.jpg","mugiwara","Figurine de Luffy à Wano");
INSERT INTO Produit VALUES (15,"Zoro",30,"img/zoro.jpeg","mugiwara","Figurine de Zoro à Wano");
INSERT INTO Produit VALUES (15,"gear 4",30,"img/g4.jpg","mugiwara","Figurine de Luffy en Gear 4");
INSERT INTO Produit VALUES (20,"Chopper",30,"img/chopper.jpg","mugiwara","Figurine de Tony Chopper à Wano");
INSERT INTO Produit VALUES (20,"Franky",30,"img/franky.jpg","mugiwara","Figurine de Franky à Wano");
INSERT INTO Produit VALUES (20,"Sanji",30,"img/sanji.jpg","mugiwara","Figurine de Sanji Vinsmoke");
INSERT INTO Produit VALUES (15,"Barbe Blanche",30,"img/barbeBlanche.jpg","pirate","Figurire de Barbe Blanche");
INSERT INTO Produit VALUES (20,"Law",30,"img/law.jpg","pirate","Figurine de Trafalgar D. Law à Wano");
INSERT INTO Produit VALUES (15,"Ace",30,"img/ace.jpg","pirate","Figurine de Portgas D. Ace");
INSERT INTO Produit VALUES (10,"Kaidou",30,"img/kaidou.jpg","pirate","Figurine du Yonkou Kaido");
INSERT INTO Produit VALUES (15,"Oden",30,"img/oden.jpg","pirate","Figurine de Oden Kozuki");
INSERT INTO Produit VALUES (15,"Mister 2",30,"img/mister2.jpg","pirate","Figurine de Mister 2");
INSERT INTO Produit VALUES (20,"Aokiji",30,"img/aokiji.jpg","marine","Figurine de l'admiral Aokiji");
INSERT INTO Produit VALUES (20,"Garp",30,"img/garp.jpg","marine","Figurine de Garp");
INSERT INTO Produit VALUES (20,"Akainu",30,"img/akainu.jpg","marine","Figurine de L'Amiral Akainu");